### ISSUE TITLE
Blocks starting X when using startx rather than using a DM

### ISSUE THREAD

**Issue by mxmilkiib** [laggardkernel/zsh-tmux#1]
I don't use a display manager. I login to a pty then run `startx`.

Because one cannot start X from within a tmux session, using `zsh-tmux` means that `startx` cannot be used in this manner.

I like the auto attach feature this plugin provides once I'm in X, but I'm not sure what workaround could resolve this issue.

**Comment by laggardkernel** [comment]
What about detecting some environment variables exported by `startx`, like loading zsh-tmux only if `DISPLAY` exists?

**Comment by mxmilkiib** [comment]
The immediate thought there would be; what about opening a second pty?

**Comment by mxmilkiib** [comment]
Trying using `[[ ! $(echo "${DISPLAY:+X11}${WAYLAND_DISPLAY:+WAYLAND}") ]] || zgen load laggardkernel/zsh-tmux`, I guess it should be ok...!
